In [5]:
import pandas as pd  #importing libraries 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [6]:
df=pd.read_csv('fraud_flags.csv')
print(df.head(10)) #importing all the datasets

   voter_id  duplicate_aadhaar_flag  multi_state_flag  multiple_votes_flag  \
0         1                       0                 0                    0
1         2                       1                 0                    0
2         3                       1                 0                    0
3         4                       1                 0                    0
4         5                       1                 0                    0
5         6                       1                 0                    0
6         7                       0                 0                    0
7         8                       1                 0                    0
8         9                       1                 0                    0
9        10                       1                 0                    0

   suspicious_score
0                 0
1                 1
2                 1
3                 1
4                 1
5                 1
6                 0
7                 1
8                 1
9                 1

In [7]:
df1=pd.read_csv('constituencies.csv')
print(df1.head())

   constituency_id constituency_name  district          state  \
0                1    Constituency_1  Tiruppur  Uttar Pradesh
1                2    Constituency_2    Howrah    Maharashtra
2                3    Constituency_3     Dehri        Gujarat
3                4    Constituency_4  Amravati          Delhi
4                5    Constituency_5    Ratlam  Uttar Pradesh

   total_population
0            108369
1            438786
2            178393
3            123158
4            103736

In [8]:
df2=pd.read_csv('fraud_flags.csv')
print(df2.head(10))

   voter_id  duplicate_aadhaar_flag  multi_state_flag  multiple_votes_flag  \
0         1                       0                 0                    0
1         2                       1                 0                    0
2         3                       1                 0                    0
3         4                       1                 0                    0
4         5                       1                 0                    0
5         6                       1                 0                    0
6         7                       0                 0                    0
7         8                       1                 0                    0
8         9                       1                 0                    0
9        10                       1                 0                    0

   suspicious_score
0                 0
1                 1
2                 1
3                 1
4                 1
5                 1
6                 0
7                 1
8                 1
9                 1

In [9]:
df3=pd.read_csv('voters.csv')
print(df3.head(10))

   voter_id        full_name  gender date_of_birth  age  aadhaar_number  \
0         1    Gaurangi Basu   Other    1964-11-08   61    703602471928
1         2     Meera Sarkar  Female    1990-10-08   35    105941298800
2         3      Liam Pingle   Other    1964-10-21   61    197945474067
3         4      Lohit Borde    Male    1984-08-20   41    542783213089
4         5   Hemangini Dyal  Female    1965-06-20   60    328171615853
5         6  Chandran Mandal  Female    1955-08-15   70    594619843437
6         7    Tanay Chaudry  Female    1964-02-11   61    725820745599
7         8        Liam Mall  Female    1953-03-06   72    337244881036
8         9      Gagan Setty   Other    1938-06-16   87    701507210982
9        10     Jack Kashyap   Other    1999-05-21   26    302655677251

   phone_number                       email  \
0  2.544079e+09      gaurangi34@example.net
1  9.122859e+11        damini98@example.net
2  4.567193e+09    yauvanipatla@example.net
3  9.173579e+11        girish99@example.net
4  8.043765e+09     sunderikbal@example.org
5  4.600369e+09   khosladevansh@example.com
6  3.985328e+08                         NaN
7  6.188050e+09       tristan52@example.com
8  9.137814e+11  chandraabhiram@example.org
9  2.061652e+09           oni72@example.net

                                    address           city       district  \
0  H.No. 582 D’Alia Chowk Bhimavaram 646972  Karawal Nagar          Surat
1             429 Shenoy Marg, Korba 576345          Hosur          Siwan
2       H.No. 23 Gandhi Nagar Kanpur 656548     Chandigarh           Kota
3               792 Din Road, Jorhat-738164         Jaipur    Bulandshahr
4              178 Bali Nagar Raipur-103035         Howrah       Durgapur
5              526 Sarkar Zila Kochi-751831     Bongaigaon      Amaravati
6          013 Parekh Road, Jabalpur-552407       Agartala          Sagar
7     70, Ahluwalia Road Miryalaguda-801257         Haldia          Dhule
8           65/839, Gour Road, Dewas-127805    Medininagar  Karawal Nagar
9      39/122, Chokshi Path Srinagar 862498      Alappuzha        Bettiah

           state  pincode registration_date
0        Gujarat   951274        2024-06-29
1          Delhi   212644        2017-02-07
2  Uttar Pradesh   472930        2023-05-26
3      Rajasthan   318929        2017-06-22
4  Uttar Pradesh    69001        2024-01-20
5      Rajasthan   224907        2025-07-03
6          Delhi   147157        2019-02-07
7  Uttar Pradesh    36911        2016-07-23
8    Maharashtra   943813        2020-07-03
9        Gujarat   545312        2020-03-24

In [10]:
df4=pd.read_csv('voting_records.csv')
print(df4.head(10))

   vote_id  voter_id  station_id   vote_date
0        1         1          19  2024-04-01
1        2         5         174  2024-04-01
2        3         6          32  2024-04-01
3        4         8          64  2024-04-01
4        5         9          99  2024-04-01
5        6        10          24  2024-04-01
6        7        12          27  2024-04-01
7        8        15          97  2024-04-01
8        9        17          78  2024-04-01
9       10        18         142  2024-04-01

In [11]:
#identifying types and shape of each datasets 
df.dtypes

voter_id                  int64
duplicate_aadhaar_flag    int64
multi_state_flag          int64
multiple_votes_flag       int64
suspicious_score          int64
dtype: object

In [12]:
df1.dtypes

constituency_id       int64
constituency_name    object
district             object
state                object
total_population      int64
dtype: object

In [13]:
df2.dtypes

voter_id                  int64
duplicate_aadhaar_flag    int64
multi_state_flag          int64
multiple_votes_flag       int64
suspicious_score          int64
dtype: object

In [14]:
df3.dtypes

voter_id               int64
full_name             object
gender                object
date_of_birth         object
age                    int64
aadhaar_number         int64
phone_number         float64
email                 object
address               object
city                  object
district              object
state                 object
pincode                int64
registration_date     object
dtype: object

In [15]:
df4.dtypes

vote_id        int64
voter_id       int64
station_id     int64
vote_date     object
dtype: object

In [16]:
#idenitifying shape of datasets
df.shape

(5000, 5)

In [17]:
df1.shape

(50, 5)

In [18]:
df2.shape

(5000, 5)

In [19]:
df3.shape

(5000, 14)

In [20]:
df4.shape

(4396, 4)

In [21]:
#Display statistical data of numerical column 
df.describe()

,voter_id,duplicate_aadhaar_flag,multi_state_flag,multiple_votes_flag,suspicious_score
count,5000.000000,5000.000000,5000.000000,5000.00000,5000.00000
mean,2500.500000,0.666400,0.034200,0.08000,0.78060
std,1443.520003,0.471546,0.181761,0.27132,0.57596
min,1.000000,0.000000,0.000000,0.00000,0.00000
25%,1250.750000,0.000000,0.000000,0.00000,0.00000
50%,2500.500000,1.000000,0.000000,0.00000,1.00000
75%,3750.250000,1.000000,0.000000,0.00000,1.00000
max,5000.000000,1.000000,1.000000,1.00000,3.00000

In [22]:
df1.describe()

       constituency_id  total_population
count         50.00000         50.000000
mean          25.50000     277461.980000
std           14.57738     136921.429511
min            1.00000      63912.000000
25%           13.25000     143355.750000
50%           25.50000     293079.500000
75%           37.75000     398704.500000
max           50.00000     484846.000000

In [23]:
df2.describe()

,voter_id,duplicate_aadhaar_flag,multi_state_flag,multiple_votes_flag,suspicious_score
count,5000.000000,5000.000000,5000.000000,5000.00000,5000.00000
mean,2500.500000,0.666400,0.034200,0.08000,0.78060
std,1443.520003,0.471546,0.181761,0.27132,0.57596
min,1.000000,0.000000,0.000000,0.00000,0.00000
25%,1250.750000,0.000000,0.000000,0.00000,0.00000
50%,2500.500000,1.000000,0.000000,0.00000,1.00000
75%,3750.250000,1.000000,0.000000,0.00000,1.00000
max,5000.000000,1.000000,1.000000,1.00000,3.00000

In [24]:
df3.describe()

          voter_id          age  aadhaar_number  phone_number        pincode
count  5000.000000  5000.000000    5.000000e+03  4.479000e+03    5000.000000
mean   2500.500000    53.550200    5.558059e+11  3.011840e+11  496867.944600
std    1443.520003    21.041094    2.563601e+11  4.264923e+11  287774.488197
min       1.000000    17.000000    1.008712e+11  8.805886e+06     372.000000
25%    1250.750000    36.000000    3.416294e+11  3.636571e+09  248083.000000
50%    2500.500000    53.000000    5.603200e+11  7.232670e+09  500557.000000
75%    3750.250000    72.000000    7.734668e+11  9.123861e+11  741183.000000
max    5000.000000    90.000000    9.999630e+11  9.199997e+11  999405.000000

In [25]:
df4.describe()

           vote_id     voter_id   station_id
count  4396.000000  4396.000000  4396.000000
mean   2198.500000  2503.158326   101.314149
std    1269.160221  1443.235648    57.958969
min       1.000000     1.000000     1.000000
25%    1099.750000  1251.000000    51.000000
50%    2198.500000  2514.000000   102.000000
75%    3297.250000  3744.000000   153.000000
max    4396.000000  5000.000000   200.000000